frameworkVersion: "^2.11.1"

service: bibliophile

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-1


package:
  exclude:
    - react-frontend/**
    - node_modules/**
    - env/**

custom:
  pythonRequirements:
    dockerizePip: true
  customDomain:
    domainName: 'api.dcain.me'
    certificateName: 'dcain.me'
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

functions:
  findBooks:
    handler: lambda.handler
    memorySize: 256
    timeout: 30
    events:
      - http:
          path: findBooks
          method: post
          cors: true
    environment:
      GOODREADS_DEV_KEY: "${env:GOODREADS_DEV_KEY}"

plugins:
  - serverless-python-requirements
  - serverless-domain-manager
