frameworkVersion: "^2.11.1"

service: bibliophile

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-1
  # Opt in to version 3 behavior eagerly
  # https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_NAME_STARTING_WITH_SERVICE
  apiGateway:
    shouldStartNameWithService: true


package:
  exclude:
    # Exclude everything by default
    # We only want to release a few modules, *not* the frontend, dev config, etc.
    - "./**"
  include:
    # Include just the functions themselves, *not* tests
    - "lambda_functions/*py"
    # Package the license & readme for good measure
    - "LICENSE.md"
    - "README.md"

custom:
  pythonRequirements:
    dockerizePip: true
    usePoetry: true
  customDomain:
    domainName: 'api.dcain.me'
    certificateName: 'dcain.me'
    basePath: 'bibliophile'
    stage: ${self:provider.stage}
    createRoute53Record: true

functions:
  readShelf:
    handler: lambda_functions.read_shelf.handler
    memorySize: 256
    timeout: 30
    events:
      - http:
          path: read_shelf
          method: post
          cors: true
    environment:
      GOODREADS_DEV_KEY: "${env:GOODREADS_DEV_KEY}"

plugins:
  - serverless-python-requirements
  - serverless-domain-manager
