const SUPPORTED_LIBRARIES = [
  {name: 'San Francisco Public Library', bibliocommonsSubdomain: 'sfpl'},
  {name: 'Seattle Public Library', bibliocommonsSubdomain: 'seattle'},
];

const BRANCHES = {
  'seattle': [
    {name: "Ballard Branch", label: "Ballard Branch"},
    {name: "Beacon Hill Branch", label: "Beacon Hill Branch"},
    {name: "Broadview Branch", label: "Broadview Branch"},
    {name: "Capitol Hill Branch", label: "Capitol Hill Branch"},
    {name: "Central Library", label: "Central Library"},
    {name: "Columbia Branch", label: "Columbia Branch"},
    {name: "Delridge Branch", label: "Delridge Branch"},
    {name: "Douglass-Truth Branch", label: "Douglass-Truth Branch"},
    {name: "Fremont Branch", label: "Fremont Branch"},
    {name: "Green Lake Branch", label: "Green Lake Branch"},
    {name: "Greenwood Branch", label: "Greenwood Branch"},
    {name: "High Point Branch", label: "High Point Branch"},
    {name: "International District/Chinatown Branch", label: "International District/Chinatown Branch"},
    {name: "Madrona-Sally Goldmark Branch", label: "Madrona-Sally Goldmark Branch"},
    {name: "Magnolia Branch", label: "Magnolia Branch"},
    {name: "Mobile Services", label: "Mobile Services"},
    {name: "Montlake Branch", label: "Montlake Branch"},
    {name: "NewHolly Branch", label: "NewHolly Branch"},
    {name: "Northeast Branch", label: "Northeast Branch"},
    {name: "Northgate Branch", label: "Northgate Branch"},
    {name: "Queen Anne Branch", label: "Queen Anne Branch"},
    {name: "Rainier Beach Branch", label: "Rainier Beach Branch"},
    {name: "South Park Branch", label: "South Park Branch"},
    {name: "Southwest Branch", label: "Southwest Branch"},
    {name: "University Branch", label: "University Branch"},
    {name: "Wallingford Branch", label: "Wallingford Branch"},
    {name: "West Seattle Branch", label: "West Seattle Branch"},
  ],
  'sfpl': [
    {name: "ANZA BRANCH", label: "Anza Branch"},
    {name: "BAYVIEW BRANCH", label: "Bayview Branch"},
    {name: "BERNAL HEIGHTS BRANCH", label: "Bernal Heights Branch"},
    {name: "CHILDREN'S BOOKMOBILE", label: "Children's Bookmobile"},
    {name: "CHINATOWN BRANCH", label: "Chinatown Branch"},
    {name: "EUREKA VALLEY BRANCH", label: "Eureka Valley Branch"},
    {name: "EXCELSIOR BRANCH", label: "Excelsior Branch"},
    {name: "GLEN PARK BRANCH", label: "Glen Park Branch"},
    {name: "GOLDEN GATE VALLEY BRANCH", label: "Golden Gate Valley Branch"},
    {name: "INGLESIDE BRANCH", label: "Ingleside Branch"},
    {name: "LIBRARY FOR THE BLIND", label: "Library for the Blind"},
    {name: "MAIN", label: "Main branch"},
    {name: "MARINA BRANCH", label: "Marina Branch"},
    {name: "MERCED BRANCH", label: "Merced Branch"},
    {name: "MISSION", label: "Mission"},
    {name: "MISSION BAY BRANCH", label: "Mission Bay Branch"},
    {name: "NOE VALLEY", label: "Noe Valley"},
    {name: "NORTH BEACH BRANCH", label: "North Beach Branch"},
    {name: "OCEAN VIEW BRANCH", label: "Ocean View Branch"},
    {name: "ORTEGA BRANCH", label: "Ortega Branch"},
    {name: "PARK BRANCH", label: "Park Branch"},
    {name: "PARKSIDE BRANCH", label: "Parkside Branch"},
    {name: "PORTOLA BRANCH", label: "Portola Branch"},
    {name: "POTRERO BRANCH", label: "Potrero Branch"},
    {name: "PRESIDIO BRANCH", label: "Presidio Branch"},
    {name: "PUBLIC KNOWLEDGE BRANCH (SFMOMA)", label: "Public Knowledge Branch (SFMOMA)"},
    {name: "RICHMOND BRANCH", label: "Richmond Branch"},
    {name: "SUNSET BRANCH", label: "Sunset Branch"},
    {name: "VISITACION VALLEY BRANCH", label: "Visitacion Valley Branch"},
    {name: "WEST PORTAL BRANCH", label: "West Portal Branch"},
    {name:   "WESTERN ADDITION BRANCH", label: "Western Addition Branch"},
  ],
};

export {SUPPORTED_LIBRARIES, BRANCHES};
